### ISSUE TITLE
bd-rhapsody does not run with universc

### ISSUE THREAD

**Issue by Davidwei7** [minoda-lab/universc#13]
Dear Sir/Madam, 

Hope you are well.

While I was waiting for a response with the issue on strt-seq, I tried with bd-rhapsody. Please see my command:`launch_universc.sh -R1 SRR5185896_sra_S1_L001_R1_001.fastq -R2 SRR5185896_sra_S1_L001_R2_001.fastq -t bd-rhapsody -r /lustre/project/m2_jgu-canshank3/Comparison/Human/HomSap_GRCh38 -i SRR5185896 -v`

Then I got the below message on my console:

script running in /lustre/project/m2_jgu-canshank3/Comparison/universc/launch_universc.sh...
... script called from /lustre/project/m2_jgu-canshank3/Comparison/universc
Running launch_universc.sh in '/lustre/project/m2_jgu-canshank3/Comparison/universc'
UniverSC Copyright (C) 2019 Tom Kelly; Kai Battenberg
This program comes with ABSOLUTELY NO WARRANTY; for details type 'cat LICENSE'. This is free software, and you are welcome to redistribute it under certain conditions; type 'cat LICENSE' for details.
Cell Ranger is called as third-party dependency and is not maintained by this project. Please ensure you comply with the End User License Agreement for all software installed where applicable; for details type 'cat README.md'.
launch_universc.sh version 1.2.5.1
cellranger version 3.0.2.9001

I am not sure whether I have done something wrong with my command input or the code for bd-rhapsody is not yet developed. Sorry for multiple posts at a short period of time. I got excited with the tool you developed.

Thank you for developing the tool, looking forward to your response. 

Best Wishes ,

David

**Comment by TomKellyGenetics** [comment]
This message is expected from verbose output. Does the code execute or fail without errors? BD Rhapsody is configured correctly in this example and preset parameters are available in the currently release.

This technology was recently release at the time of development and has not been extensively tested. Let us know if you have further issues with it.
