### ISSUE TITLE
Issue for bd-rhapsody setup

### ISSUE THREAD

**Issue by stat-lab** [minoda-lab/universc#18]
Thank you for providing valuable tools.
I used the latest universc (v1.2.6) and tried to run setup command for bd-rhapsody-v2.
The result shows "barcode adjust: 0" and the failure for the absence of several files.
I am using cellranger v7.2.0, but the result was obtained even when using cellranger v4.0.0.
My command and messages on the console are as follows:

launch_universc.sh -t bd-rhapsody-v2 --setup

script running in /home/tools/universc/launch_universc.sh...
... script called from /home/tools/universc
Running launch_universc.sh in '/home/tools/universc'
UniverSC Copyright (C) 2019 Tom Kelly; Kai Battenberg
This program comes with ABSOLUTELY NO WARRANTY; for details type 'cat LICENSE'. This is free software, and you are welcome to redistribute it under certain conditions; type 'cat LICENSE' for details.
Cell Ranger is called as third-party dependency and is not maintained by this project. Please ensure you comply with the End User License Agreement for all software installed where applicable; for details type 'cat README.md'.
Using 10x version 2 chemistry to support UMIs
***WARNING: conversion was turned on because directory input4cellranger_ was not found***
 checking if UniverSC is running already
  creating .lock file

#####Input information#####
SETUP and exit: true
***WARNING: launch_universc.sh will exit once whitelist is converted***
FORMAT: bd-rhapsody-v2
BARCODES: /home/tools/universc/whitelists/bd_rhapsody_barcode.txt
***WARNING: no FASTQ files were selected, launch_universc.sh will exit after setting up the whitelist***
SAMPLE: 
LANE: 
ID: 
DESCRIPTION: 
***WARNING: no description given, setting to ID value***
REFERENCE: 
NCELLS: (no cell number given)
CHEMISTRY: SC3Pv2
JOBMODE: local
***WARNING: --jobmode "sge" is recommended if running script with qsub***
CONVERSION: true
##########

whitelist setup begin
updating barcodes in /home/tools/cellranger-7.2.0/lib/python/cellranger/barcodes for Cell Ranger version cellranger-7.2.0 installed in /home/tools/cellranger-7.2.0/cellranger ...
 restoring Cell Ranger
cp: '/home/tools/cellranger-7.2.0/cellranger-cs/cellranger-7.2.0/lib/python/cellranger/webshim/template/navbar.html' Cannot stat: No such file or directory
cp: '/home/tools/cellranger-7.2.0/cellranger-cs/cellranger-7.2.0/lib/python/cellranger/webshim/template/navbar.html' Cannot stat: No such file or directory
sed: /home/tools/cellranger-7.2.0/cellranger-cs/cellranger-7.2.0/lib/python/cellranger/check.py Cannot read: No such file or directory
 /home/tools/cellranger-7.2.0/cellranger set for bd-rhapsody-v2
 converting whitelist
barcode adjust: 0
 whitelist converted
verbose 
setup complete
running in local mode (no cluster configuration needed)
 setup complete. exiting launch_universc.sh

**Comment by g0656116** [comment]
I was wondering if you solved the issue.
We are experiencing the same difficulties

**Comment by kbattenb** [comment]
I am glad you found UniverSC interesting.
Due to IP issues, UniverSC cannot offer help when versions of cellranger beyond 3.0.2 is used.
Please try using the open sourced cellranger 3.0.2 instead of 7.2.0 to see if the error still occurs.

**Comment by stat-lab** [comment]
Thank you for your response.
I used cellranger v3.0.2 to run UniverSC, and the setup satge seemed to be successful.
But in the cellranger run process, I encountered an error, resulting in incomplete run.
The error log indicates the following message.

CalledProcessError: Command '['chunk_reads', '--reads-per-fastq', '5000000', '.../SC_RNA_COUNTER_CS/SC_RNA_COUNTER/_BASIC_SC_RNA_COUNTER/CHUNK_READS/fork0/chnk0-uea9b89dd50/files/', 'fastq_chunk', '--martian-args', 'chunk_args.json', '--compress', 'lz4']' returned non-zero exit status 1

It would be helpful if you could make some comments to resolve this problem.
