### ISSUE TITLE
BD-rhapsody data analysis 

### ISSUE THREAD

**Issue by g0656116** [minoda-lab/universc#19]
I would like to analyze single cell RNASeq data obtained from BD using your Universc.
The contents below describe the process from the installation of universc to the current running status.

###universc  installation

#root@Song:/home/song# git clone https://github.com/minoda-lab/universc.git
Cloning into 'universc'...
remote: Enumerating objects: 5307, done.
remote: Counting objects: 100% (504/504), done.
remote: Compressing objects: 100% (199/199), done.
remote: Total 5307 (delta 318), reused 481 (delta 295), pack-reused 4803
Receiving objects: 100% (5307/5307), 299.91 MiB | 3.34 MiB/s, done.
Resolving deltas: 100% (3400/3400), done.
Updating files: 100% (215/215), done.
Filtering content: 100% (44/44), 249.31 MiB | 3.13 MiB/s, done.
Encountered 1 file that should have been a pointer, but wasn't:
	test/shared/cellranger-tiny-fastq/1.2.0/read-RA_si-TTTCATGA_lane-008-chunk-001.fastq.gz

###BD-rhasody setup 

#song@Song:~/다운로드/universc$ bash launch_universc.sh -t "bd-rhapsody" --setup
cript running in /home/song/다운로드/universc/launch_universc.sh...
... script called from /home/song/다운로드/universc
'.' resolves to '/home/song/다운로드/universc'
Running launch_universc.sh in '/home/song/다운로드/universc'
UniverSC Copyright (C) 2019 Tom Kelly; Kai Battenberg
This program comes with ABSOLUTELY NO WARRANTY; for details type 'cat LICENSE'. This is free software, and you are welcome to redistribute it under certain conditions; type 'cat LICENSE' for details.
Cell Ranger is called as third-party dependency and is not maintained by this project. Please ensure you comply with the End User License Agreement for all software installed where applicable; for details type 'cat README.md'.
Using 10x version 2 chemistry to support UMIs
***WARNING: conversion was turned on because directory input4cellranger_ was not found***
 checking if UniverSC is running already
  creating .lock file

#####Input information#####
SETUP and exit: true
***WARNING: launch_universc.sh will exit once whitelist is converted***
FORMAT: bd-rhapsody
BARCODES: /home/song/다운로드/universc/whitelists/bd_rhapsody_barcode.txt
***WARNING: no FASTQ files were selected, launch_universc.sh will exit after setting up the whitelist***
SAMPLE: 
LANE: 
ID: 
DESCRIPTION: 
***WARNING: no description given, setting to ID value***
REFERENCE: 
NCELLS: (no cell number given)
CHEMISTRY: SC3Pv2
JOBMODE: local
***WARNING: --jobmode "sge" is recommended if running script with qsub***
CONVERSION: true
##########

whitelist setup begin
updating barcodes in /home/song/Cell_Ranger/cellranger-7.2.0/lib/python/cellranger/barcodes for Cell Ranger version cellranger-7.2.0 installed in /home/song/Cell_Ranger/cellranger-7.2.0/cellranger ...
 restoring Cell Ranger
cp: cannot stat '/home/song/Cell_Ranger/cellranger-7.2.0/cellranger-cs/cellranger-7.2.0/lib/python/cellranger/webshim/template/navbar.html': No such file or directory
cp: cannot stat '/home/song/Cell_Ranger/cellranger-7.2.0/cellranger-cs/cellranger-7.2.0/lib/python/cellranger/webshim/template/navbar.html': No such file or directory
sed: can't read /home/song/Cell_Ranger/cellranger-7.2.0/cellranger-cs/cellranger-7.2.0/lib/python/cellranger/check.py: No such file or directory
 /home/song/Cell_Ranger/cellranger-7.2.0/cellranger set for bd-rhapsody
 converting whitelist
barcode adjust: 0
 whitelist converted
verbose 
setup complete
running in local mode (no cluster configuration needed)
 setup complete. exiting launch_universc.sh

###analyze BD-rhasody(*.fastq)
song@Song:~/다운로드/universc$ bash launch_universc.sh  --id "MJ" --technology "bd-rhapsody" --reference "test/cellranger_reference/cellranger-tiny-ref/3.0.0" --read1 "/home/song/Raw_data/NGS230926_S1_L001_R1_001" --read2 "/home/song/Raw_data/NGS230926_S1_L001_R2_001" --localcores 16 --localmem 64
script running in /home/song/다운로드/universc/launch_universc.sh...
... script called from /home/song/다운로드/universc
'.' resolves to '/home/song/다운로드/universc'
Running launch_universc.sh in '/home/song/다운로드/universc'
UniverSC Copyright (C) 2019 Tom Kelly; Kai Battenberg
This program comes with ABSOLUTELY NO WARRANTY; for details type 'cat LICENSE'. This is free software, and you are welcome to redistribute it under certain conditions; type 'cat LICENSE' for details.
Cell Ranger is called as third-party dependency and is not maintained by this project. Please ensure you comply with the End User License Agreement for all software installed where applicable; for details type 'cat README.md'.
    /home/song/Raw_data/NGS230926_S1_L001_R1_001.fastq file found
    /home/song/Raw_data/NGS230926_S1_L001_R2_001.fastq file found
Using 10x version 2 chemistry to support UMIs
***WARNING: conversion was turned on because directory input4cellranger_MJ was not found***
 checking if UniverSC is running already
  creating .lock file

#####Input information#####
SETUP and exit: false
FORMAT: bd-rhapsody
BARCODES: /home/song/다운로드/universc/whitelists/bd_rhapsody_barcode.txt
INPUT(R1):
 /home/song/Raw_data/NGS230926_S1_L001_R1_001.fastq
INPUT(R2):
 /home/song/Raw_data/NGS230926_S1_L001_R2_001.fastq
SAMPLE: NGS230926
LANE: 1
ID: MJ
DESCRIPTION: MJ
***WARNING: no description given, setting to ID value***
REFERENCE: test/cellranger_reference/cellranger-tiny-ref/3.0.0
NCELLS: (no cell number given)
CHEMISTRY: SC3Pv2
JOBMODE: local
***WARNING: --jobmode "sge" is recommended if running script with qsub***
CONVERSION: true
##########

whitelist setup begin
updating barcodes in /home/song/Cell_Ranger/cellranger-7.2.0/lib/python/cellranger/barcodes for Cell Ranger version cellranger-7.2.0 installed in /home/song/Cell_Ranger/cellranger-7.2.0/cellranger ...
 restoring Cell Ranger
cp: cannot stat '/home/song/Cell_Ranger/cellranger-7.2.0/cellranger-cs/cellranger-7.2.0/lib/python/cellranger/webshim/template/navbar.html': No such file or directory
cp: cannot stat '/home/song/Cell_Ranger/cellranger-7.2.0/cellranger-cs/cellranger-7.2.0/lib/python/cellranger/webshim/template/navbar.html': No such file or directory
sed: can't read /home/song/Cell_Ranger/cellranger-7.2.0/cellranger-cs/cellranger-7.2.0/lib/python/cellranger/check.py: No such file or directory
 /home/song/Cell_Ranger/cellranger-7.2.0/cellranger set for bd-rhapsody
 converting whitelist
barcode adjust: 0
 whitelist converted
verbose 
setup complete
running in local mode (no cluster configuration needed)
creating a folder for all Cell Ranger input files ...
 directory input4cellranger_MJ created for converted files
moving file to new location
 handling /home/song/Raw_data/NGS230926_S1_L001_R1_001.fastq ...
 handling /home/song/Raw_data/NGS230926_S1_L001_R2_001.fastq ...
converting input files to confer cellranger format ...
 adjustment parameters:
  barcodes: 0 bp at its head
  UMIs: -2 bp at its tail
 making technology-specific modifications ...
  ... remove adapter and phase blocks for bd-rhapsody
  ... remove adapter and phase blocks for bd-rhapsody

---------------------------------------------------------------------------------------------------------
![Screenshot from 2023-12-25 16-45-06](https://github.com/minoda-lab/universc/assets/85277794/f9b709df-7421-4919-b6a8-852769413d3a)

If you look at the screenshot, it looks like something is going on. 
I'm not sure if this has stopped or is ongoing. Did something go wrong during the process?
Please tell me what I should fix

**Comment by kbattenb** [comment]
Hi,

Due to IP issues, we cannot help you if cellranger-7.2.0 is used with UniverSC.
Please try using the open access version of cellranger 3.0.2 instead.
If you still run into problems, we can help you again.

Kai Battenberg
