### ISSUE TITLE
Error for test run nadia platform

### ISSUE THREAD

**Issue by amufaamo** [minoda-lab/universc#6]
Hi, I got an error below. I don't know what happened. Could you give me some advice?

I think perl makes this trouble, but I dont know how to solve this.

launch_universc.sh -R1 universc/test/shared/dropseq-test/SRR1873277_Sample1_R1.fastq.gz -R2 universc/test/shared/dropseq-test/SRR1873277_Sample1_R2.fastq.gz -t nadia -i 220330_test_nadia -r cellranger/reference/refdata-gex-GRCh38-2020-A
'/user/users/universc' resolves to '/auto/user/users/universc'
Running launch_universc.sh in '/auto/users/universc'
UniverSC Copyright (C) 2019 Tom Kelly; Kai Battenberg
This program comes with ABSOLUTELY NO WARRANTY; for details type 'cat LICENSE'. This is free software, and you are welcome to redistribute it under certain conditions; type 'cat LICENSE' for details.
Cell Ranger is called as third-party dependency and is not maintained by this project. Please ensure you comply with the End User License Agreement for all software installed where applicable; for details type 'cat README.md'.
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Error: /user/users/universc/test/shared/dropseq-test/SRR1873277_Sample1_R1.fastq.gz not found

**Comment by TomKellyGenetics** [comment]
Hi, sorry to hear you have trouble using our tool. This seems to be an issue with your locale settings but it is a warning. Please check that Perl and your shell are configured correctly.

The error seems to be missing input files. Please also check that the files have been downloaded correctly and are compressed in gz format. The paths look unusual compared to Mac or Linux systems so it is hard to know if they are correct.

If you are using our test data included with the GitHub repository please note you need [Git LFS](https://git-lfs.github.com/) installed. These are not downloaded by `git clone` but requires additional commands: `git lfs pull origin master`

If the problems persist please share more details on your system such as operating system and which version of UniverSC you have installed. Thank you.
