### ISSUE TITLE
[error] Lanes must be a comma-separated list of numbers

### ISSUE THREAD

**Issue by hibiscuslee** [minoda-lab/universc#8]
Dear Kai,
Good idea with the program，which can be applicable to split-seq that just what i need.
I am having difficulties running the script:

Running preflight checks (please wait)...
11:58:14 [runtime] (ready)           ID.SRR.SC_RNA_COUNTER_CS.EXPAND_SAMPLE_DEF
11:58:14 [runtime] (run:local)       ID.SRR.SC_RNA_COUNTER_CS.EXPAND_SAMPLE_DEF.fork0.chnk0.main
11:59:06 [runtime] (chunks_complete) ID.SRR.SC_RNA_COUNTER_CS.EXPAND_SAMPLE_DEF
Checking sample info...
Checking FASTQ folder...

[error] Lanes must be a comma-separated list of numbers.

my command :
bash launch_universc.sh -R1 "../raw_data/SRR6750053_S1_L001_R1_001.fastq" -R2 "../raw_data/SRR6750053_S1_L001_R2_001.fastq" -i SRR -r "test/cellranger_reference/refdata-gex-mm10-2020-A" -t "splitseq" -b "whitelists/split-seq_round1_barcodes.txt" "whitelists/split-seq_round2_barcodes.txt" "whitelists/split-seq_round3_barcodes.txt"

if you need, there are the first few rows of the files：
#head -n 24 SRR6750053_S1_L001_R1_001.fastq
@SRR6750053.1 1/1
CTATTNAACCCTCTGAGTTTGCCCCTGTTGTGTCCCTGAGCATGTCTGTCTCTTTTCTTGGTCCTT
+
AAAAA#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEAEEEEEAEEEEEE
@SRR6750053.2 2/1
CACCCNCACTTCCGGAGGTCTTCTCACTTCAATTACCTTAGTCTTGAAAATCTCTTGAGGACATTT
+
AAAAA#EEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEEEEEEEEAE
@SRR6750053.3 3/1
ATAATNAATAAATCCCAAAAAAAAAAAAAATGAATATTCTAAAGCAAAGGAATAAAAAGAACGTGG
+
A6AAA#6EAEEEE/EEE/EE/EEEEEEE//<//E/E/////<//A///////////A<//////</
@SRR6750053.4 4/1
GCTCTNGCCTCTCAAGCACGTGGATTTCCTGCTAGTCGTACGCCGATGCGAAACATCTGCCACTCT
+
AAAAA#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
@SRR6750053.5 5/1
TGATANAGGAGTCGTACGCCGATGCGAAACATCTGCCACGTGTCCTTCACCGAGGCTAGATCGGAA
+
AAAAA#EEEAEEEEE/AEEEE6EEEEEEEEEEEEEEEEEEEEEAEEEE/EAEEEEEEEE6AEEEE/
@SRR6750053.6 6/1
ATAGCNCATAAGTAGCAGAACACTGGAAGCTTAGATTTCCCACGTACATCTCGAATGCTCTGGCCT
+
AAAAA#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEAEEE

#head -n 24 SRR6750053_S1_L001_R2_001.fastq
@SRR6750053.1 1/2
NNGTTCCGGATTGGCTCGTGGCCGATGTTTCGCATCGGCGTACGACTACTATGCAATCAACGTGCTTGAGAGGCCAGAGCATTCGACTATGCAT
+
##AAAEEEEAEEAAEEEEEE/EEA/6/</A/<6<A<<6E/AE<</<A/<AAAAAEEEE66A6</A</6<AAA/EEAEAAEAAEA6<EEAEAA<E
@SRR6750053.2 2/2
NNGTTTCTTACAATGGAAGTGGCCGCTGTTTCGCATCGGCGTACGACTCAGCGTTAATCCACGTGCTTGAGAGGACAGAGCATTCGAGATCGCA
+
##/AAEE/EE/EE/EEEAE/EE//E///A///6666/EAAA6/6666/6EAEAEA</<</A/E6/66/6<AA<AE<AE/EE///<AAA/A/A//
@SRR6750053.3 3/2
NNGTGGTTCCAGCACCTCGTGGCCGCTGTTTCGCATCGGCGTACGACTCTACCAAATCCACCTGCTTTAGAGGCCAGAGCAATCGACTATGCAT
+
##/AAEE/EA/A<EEEEEE/EEAEE6<EAA/66666<EEAAEA6</A////6EAEE///6A///////6/E/</E/<A/<E/</<E6<EA////
@SRR6750053.4 4/2
NNCCGGCGAAGTCGTAGAGTGGCAGCTGTTTCGCATCGGCGTACGACTAGCAGGAAATCCACGTGCTTGAGAGGCCAGAGCCTGTCTCTTATAC
+
##AAAEEEEEEEEEEEEEE/EE//E6<AAA<66666<EEAEEA6AAAEEEEEEEEEEEEEEEE6<<A6<EEEEEEEEEEEEEAEEEEAEEEEEE
@SRR6750053.5 5/2
NNCCTCGGTGAAGGACACGGGGCAGCTGTTTCGCATCGGCGTACGACTCCTCTATCACTGTCTCTTATACACATCTGACGCTGCCGACGAGCGA
+
##AAAEAEEEEEEEEEEEE/6E<<E6AEAE/666/6AEA6AE<6A/AAA<EEE</EE/<<<AAA<</<EE/AAA<6<EE<E<A<<AAAE/EEE<
@SRR6750053.6 6/2
NNGTTAAAAGATCATTCCGTGGGCGCTGTTTCGCATCGGCGTACGACTCACCTTACATCCACGTGCTTGAGAGGCCAGAGCATTCGAGATGTAC
+
##AA/AAA/E/EEAAEEAE/EE/EE//<A//66666/AA6AA<6666/<////<<EE//6<<A6666/66EEAEE/AE<EAE6<EAEE<<E<AE

# head -n 24 R22019033_S1_L001_R1_001.fastq
@A01225:473:HG7M5DSX3:1:1101:1371:1016 1:N:0:CAGATC+ATAGAGAG
TNATAATACTGGAAATGGGACCTTCTGTCATTGTGATGAGAAAGTAAGTTCATTTAACTTACAGGCAGTCTTGTCCCTTGTAATAACTGCAGCCCAGAATCAATATATTTTTTCAGAGAAAGTTATCCACTCAATTTTTTCTGATTTATA
+
F#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF:F:F:FFFFFFFFFFFF
@A01225:473:HG7M5DSX3:1:1101:3161:1016 1:N:0:CAGATC+ATAGAGAG
CNAAAGGATGACATTCCGGGTTTAGTGAGAAACCTTTTCCTCAAAAAATAAAAAAAAAAAAAAAATCTGCTGTCGAATGCTCTGGCCTCTCAAGCACGTGGATTGTATGCGAGTCGTACGCCGATGCGAAACATCGGCCACGGCTACAGG
+
F#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFF:FFFFFFFFF,,FFF:FFFFFFFFFFFFFFFFFF:FFFFF:FFFFFFFF,FFFFF:F,FFFFFFFFFFFFFFFF,::,:F:FFF,FFFFFFFFFF
@A01225:473:HG7M5DSX3:1:1101:3179:1016 1:N:0:CAGATC+ATAGAGAG
TNCATGGGTAAAGGAATCTCAGATGACTTCAGCAAAGGGCCATATTCAAAACTGCTCTCAGAGGGAAAATCTGTTGTCACTGAATTAATGGCCATCACCTGGCCCCCTGCAATCTGTAAGTCATAATAATTCTTGCAAATACTTTTGCAA
+
F#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:,F
@A01225:473:HG7M5DSX3:1:1101:3215:1016 1:N:0:CAGATC+ATAGAGAG
GNGTGTGTGTATGAGGTGAAACAGTTTAATAAAACCTTAGAAAAAAAAAAAAAAATGCGATCTCGAATGCTCTGGCCTCTCAAGCACGTGGATTCTCGGTTAGTCGTACGCCGATGCGAAACATCGGCCACACTTGATGGAGAGCGCACA
+
F#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFF:FFFFFFFFFFFFFFFF
@A01225:473:HG7M5DSX3:1:1101:3269:1016 1:N:0:CAGATC+ATAGAGAG
TNGAAATATTACTTAGTCTTAATAATCTAAGAAGATCTTAAGAGATAACATGAAGGCTTATTTAAACAGTTTGAAAAAGGAAATGAGGAGAAAAGTATTTGTACTGTATAATGGAGGCTGACCAGAGCAGTTTAGGAGATTGTAAAGGGA
+
:#FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F:FFFFFFFFFFF:FFFFF
@A01225:473:HG7M5DSX3:1:1101:3287:1016 1:N:0:CAGATC+ATAGAGAG
ANTTAGGCATAGTCGTACGCCGATGCGAAACATCGGCCACTGAACTGGATATGCGGTCAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCGGCGTGTAAATGGGGGGGGGGGGGGGGGGGGGGG
+
F#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F,FFF,F::FF,,,,,,F,,,F,,,,,:FFFFFFFFFFFFFFFFFFFFFF

#head -n 24 R22019033_S1_L001_R2_001.fastq
@A01225:473:HG7M5DSX3:1:1101:1371:1016 2:N:0:CAGATC+ATAGAGAG
GCACTTGAGGAGCACAAGGTGGCCGATGTTTCGCATCGGGCGTACGACTACCTCCAAATCCACGTGCTTGAGAGGCCAGAGCATTCGCGCTGATCTTTTTTTTTTTTTTTGCATTTTATCAGAAAGTTTAATTATAAATCAGAAAAAATT
+
FFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFF:FF:F::F:FFFFFF::F
@A01225:473:HG7M5DSX3:1:1101:3161:1016 2:N:0:CAGATC+ATAGAGAG
TTGAGAATGCCTGTAGCCGTGGCCGATGTTTCGCATCGGCGTACGACTCGCATACAATCCACGTGCTTGAGAGGCCAGAGCATTCGACAGCAGATTTTTTTTTTTTTTTTATTTTTTGAGGAAAAGGTTTCTCACTAAACCCGGAATGTC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFF:FFFFFFFFFFFFFFF::FFFFFFFFF,FFFFFFFF:FF,FFFFFFFFFFFFFFFFFFF
@A01225:473:HG7M5DSX3:1:1101:3179:1016 2:N:0:CAGATC+ATAGAGAG
GGGGAAAAGGAAGAGGAGACAAATTCTGTTGCTACCCTTTCCTATTCCTCTGTGGATGAAACACAAGTCAGAAGTCTCTACGTGAGCTGCAAATCATCTGGCAAGTTTATCTCTTCAGTGCATTCAAGAGAGAGCCAACATAGCAGAAGT
+
FFFFFFFFFF:FFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFF:,:FFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFF:FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF
@A01225:473:HG7M5DSX3:1:1101:3215:1016 2:N:0:CAGATC+ATAGAGAG
GTGCGCTCTCCATCAAGTGTGGCCGATGTTTCGCATCGGCGTACGACTAACCGAGAATCCACGTGCTTGAGAGGCCAGAGCATTCGAGATCGCATTTTTTTTTTTTTTTGTAAGGTTTTATTAAACTGTTTCACCTCATACACACACACC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF:FF:F:FF,FF:::FFFF:FFFFF,FFFFFF:FF,,FFFFF:,:F:FF,
@A01225:473:HG7M5DSX3:1:1101:3269:1016 2:N:0:CAGATC+ATAGAGAG
TCTCGTCTGCCGCATACAGTGGCCGATGTTTCGCATCGGCGTACGACTACAAGCTAATCCACGTGCTTGAGAGGCCAGAGCATTCGAGTCACTATTTTTTTTTTTTTCAACTACACCTCATTTTCAAACTATTCTCTACAACTTTACTGT
+
FFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFF:FFFFFFFFFFFF,FFFFFF:::F:FFFFFFFFFFFFF,,,F:FF:FFFFF:FFFFFFF::FFF,FFF,F,,FFFFFFFFF
@A01225:473:HG7M5DSX3:1:1101:3287:1016 2:N:0:CAGATC+ATAGAGAG
GACCGCATATCCAGTTCAGTGGCCGATGTTTCGCATCGGCGTACGACTATGCCTAAATCTGTCTCTTATACACATCTGACGCTGCCGACGAATAGAGAGGTGTAGATCTCGGTGGTCGCCGTATCATTAAAAAAAAATTTTTTGAAGCAG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:::FFFF,F,:,:,:F

system: shell
JOBMODE: local
cellranger: 3.0.2 from the 10X genomics

thanks for this tool, and looking forward to your response
xiangli

**Comment by kbattenb** [comment]
Hi Xiang,

It’s great that people are showing interest in our tool:)

Would you mind telling me what version of UniverSC you are using? (I am assuming it is version 1.2.4)
Also, would you mind running the test 10x dataset that we provide to make sure that UnverSC can run without issues?

If it is version 1.2.4, and if 10x dataset does runs without issues, I think I know what may be happening.

Please let me know.

Kai Battenberg

**Comment by hibiscuslee** [comment]
Hi Kai,
Thanks for your advice!
The version of UniverSC is 1.2.4, and when i run with the 10x dataset, firstly, the warning is about the barcode file; and then it has the same error:

Running preflight checks (please wait)...
2023-01-18 16:05:11 [runtime] (ready)           ID.test-10x-v3.SC_RNA_COUNTER_CS.EXPAND_SAMPLE_DEF
2023-01-18 16:05:11 [runtime] (run:local)       ID.test-10x-v3.SC_RNA_COUNTER_CS.EXPAND_SAMPLE_DEF.fork0.chnk0.main
2023-01-18 16:05:51 [runtime] (chunks_complete) ID.test-10x-v3.SC_RNA_COUNTER_CS.EXPAND_SAMPLE_DEF
Checking sample info...
Checking FASTQ folder...

[error] Lanes must be a comma-separated list of numbers.

**Comment by kbattenb** [comment]
Hi Xiang,

Actually your timing could not have been better.
I was actually running into similar issues too, and we now (like 15 minutes ago) have pushed version 1.2.5.
This one solved the issue for me (although I was testing it with 10x and ICELL8 data).

Hopefully, version 1.2.5 solves the issue for you.
Please let me know if that fails too.

Thank you.

Kai Battenberg

**Comment by TomKellyGenetics** [comment]
Thanks for reporting this issue. I’ve merged the solution from the dev version (as already planned). Try pulling the “master” branch again and let us know if you have any problems with the new version.

closed by 1.2.5
